### ISSUE TITLE
Short descriptions needed for missing webinars

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/cms#5]
Short descriptions needed for:
- [x] Web Design is Hard
- [x] Right-Sizing Your Rapid Prototypes
- [x] Designing for Understanding
- [x] Designing for Real People

**Add short descriptions to this issue thread**

 Reference: https://github.com/gymnasium/cms/blob/master/todo.md

**Comment by jgagne** [comment]
# Right-Sizing Your Rapid Prototypes

A conversation about choosing the appropriate fidelity of breadth, depth, and content for rapid prototyping with special guests Erin Young and Tracy Singleton.

Preview: https://gymnasium.github.io/cms/webinars/right-sizing-your-rapid-prototypes/

**Comment by jgagne** [comment]
# Designing for Understanding

 A conversation about how content, UX, and design work together to create meaningful interactions with special guests Stephanie Hay and John Hodgins.

Preview: https://gymnasium.github.io/cms/webinars/designing-for-understanding/

**Comment by jgagne** [comment]
# Designing for Real People

A conversation about the benefits of user research and making the case to stakeholders on how to get it done right with special guests Eric Meyer and Jim Webb.

Preview: https://gymnasium.github.io/cms/webinars/designing-for-real-people/
